//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenterManagement_MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainingCenterManagement_MVC.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the menu.
        /// </summary>
        internal static string accessToMenu {
            get {
                return ResourceManager.GetString("accessToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string active_status {
            get {
                return ResourceManager.GetString("active_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Payment Method.
        /// </summary>
        internal static string add_payment_method_button {
            get {
                return ResourceManager.GetString("add_payment_method_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Menu.
        /// </summary>
        internal static string AddMenu_Button {
            get {
                return ResourceManager.GetString("AddMenu_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Menu Title.
        /// </summary>
        internal static string AddNewMenu_Title {
            get {
                return ResourceManager.GetString("AddNewMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Email.
        /// </summary>
        internal static string Admin_Email {
            get {
                return ResourceManager.GetString("Admin_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Login.
        /// </summary>
        internal static string Admin_Login {
            get {
                return ResourceManager.GetString("Admin_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin login.
        /// </summary>
        internal static string AdminAuth_Title {
            get {
                return ResourceManager.GetString("AdminAuth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        internal static string adminDashboard {
            get {
                return ResourceManager.GetString("adminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage system data, monitor requests and update menus..
        /// </summary>
        internal static string AdminDashboard_Description {
            get {
                return ResourceManager.GetString("AdminDashboard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard .
        /// </summary>
        internal static string AdminDashboard_Header {
            get {
                return ResourceManager.GetString("AdminDashboard_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        internal static string AdminDashboard_Subtitle {
            get {
                return ResourceManager.GetString("AdminDashboard_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        internal static string AdminDashboard_Title {
            get {
                return ResourceManager.GetString("AdminDashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@tabletap.com.
        /// </summary>
        internal static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Navigation .
        /// </summary>
        internal static string AdminNavigation {
            get {
                return ResourceManager.GetString("AdminNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin User .
        /// </summary>
        internal static string AdminUser {
            get {
                return ResourceManager.GetString("AdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Types.
        /// </summary>
        internal static string all_types_option {
            get {
                return ResourceManager.GetString("all_types_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string allRightsReserved {
            get {
                return ResourceManager.GetString("allRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string Analytics {
            get {
                return ResourceManager.GetString("Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed analytics about restaurant onboarding and activity. .
        /// </summary>
        internal static string Analytics_RestaurantDescription {
            get {
                return ResourceManager.GetString("Analytics_RestaurantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Analytics .
        /// </summary>
        internal static string Analytics_RestaurantTitle {
            get {
                return ResourceManager.GetString("Analytics_RestaurantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed analytics about subscription revenue and growth. .
        /// </summary>
        internal static string Analytics_RevenueDescription {
            get {
                return ResourceManager.GetString("Analytics_RevenueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Analytics .
        /// </summary>
        internal static string Analytics_RevenueTitle {
            get {
                return ResourceManager.GetString("Analytics_RevenueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed analytics about user registration and engagement. .
        /// </summary>
        internal static string Analytics_UserDescription {
            get {
                return ResourceManager.GetString("Analytics_UserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Analytics .
        /// </summary>
        internal static string Analytics_UserTitle {
            get {
                return ResourceManager.GetString("Analytics_UserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only authorized administrators can access this panel..
        /// </summary>
        internal static string authorized {
            get {
                return ResourceManager.GetString("authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Transfer.
        /// </summary>
        internal static string BankTransfer {
            get {
                return ResourceManager.GetString("BankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic service at a small price with more expensive options for more customizations..
        /// </summary>
        internal static string basicServiceAtSmallPrice {
            get {
                return ResourceManager.GetString("basicServiceAtSmallPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        internal static string careers {
            get {
                return ResourceManager.GetString("careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string cash {
            get {
                return ResourceManager.GetString("cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Category] analytics will appear here .
        /// </summary>
        internal static string ChartPlaceholder_GenericText {
            get {
                return ResourceManager.GetString("ChartPlaceholder_GenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics chart will appear here .
        /// </summary>
        internal static string ChartPlaceholder_Text {
            get {
                return ResourceManager.GetString("ChartPlaceholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, the client can only use the browser to access the menu..
        /// </summary>
        internal static string clientUseBrowser {
            get {
                return ResourceManager.GetString("clientUseBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Scheme.
        /// </summary>
        internal static string colorScheme {
            get {
                return ResourceManager.GetString("colorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure available payment methods for the platform..
        /// </summary>
        internal static string configure_available_methods {
            get {
                return ResourceManager.GetString("configure_available_methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        internal static string cookies {
            get {
                return ResourceManager.GetString("cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost savings.
        /// </summary>
        internal static string costSavings {
            get {
                return ResourceManager.GetString("costSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a QR Code.
        /// </summary>
        internal static string createQR {
            get {
                return ResourceManager.GetString("createQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptocurrency.
        /// </summary>
        internal static string Cryptocurrency {
            get {
                return ResourceManager.GetString("Cryptocurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join many of establishments already using TableTap to enhance their dining experience..
        /// </summary>
        internal static string ctaSectionDescription {
            get {
                return ResourceManager.GetString("ctaSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Transform Your Establishment?.
        /// </summary>
        internal static string ctaSectionHeading {
            get {
                return ResourceManager.GetString("ctaSectionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers can access the menu via QR code easily without downloading an app..
        /// </summary>
        internal static string customersAccessQR {
            get {
                return ResourceManager.GetString("customersAccessQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer satisfaction.
        /// </summary>
        internal static string customerSatisfaction {
            get {
                return ResourceManager.GetString("customerSatisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers use their phones to scan the code and access the digital menu instantly..
        /// </summary>
        internal static string customersUsePhones {
            get {
                return ResourceManager.GetString("customersUsePhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string customize {
            get {
                return ResourceManager.GetString("customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Card.
        /// </summary>
        internal static string DebitCard {
            get {
                return ResourceManager.GetString("DebitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital menu platform for establishments. Create and share menus via QR codes..
        /// </summary>
        internal static string digitalMenuPlatform {
            get {
                return ResourceManager.GetString("digitalMenuPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        internal static string Drinks {
            get {
                return ResourceManager.GetString("Drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease of access.
        /// </summary>
        internal static string EaseAccess {
            get {
                return ResourceManager.GetString("EaseAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can the menu be easily customized?.
        /// </summary>
        internal static string easilyCustomized {
            get {
                return ResourceManager.GetString("easilyCustomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 Easy, fast, and sustainable..
        /// </summary>
        internal static string easyFast {
            get {
                return ResourceManager.GetString("easyFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Payment Method.
        /// </summary>
        internal static string edit_payment_method_button {
            get {
                return ResourceManager.GetString("edit_payment_method_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email us:.
        /// </summary>
        internal static string emailUs {
            get {
                return ResourceManager.GetString("emailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter admin email.
        /// </summary>
        internal static string Enter_admin_email {
            get {
                return ResourceManager.GetString("Enter_admin_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter payment method description.
        /// </summary>
        internal static string enter_method_description_placeholder {
            get {
                return ResourceManager.GetString("enter_method_description_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter payment method name.
        /// </summary>
        internal static string enter_method_name_placeholder {
            get {
                return ResourceManager.GetString("enter_method_name_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental protection.
        /// </summary>
        internal static string environmentalProtection {
            get {
                return ResourceManager.GetString("environmentalProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment.
        /// </summary>
        internal static string Establishment {
            get {
                return ResourceManager.GetString("Establishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌍 Jump into your establishment&apos;s digital future..
        /// </summary>
        internal static string establishmentDigitalFuture {
            get {
                return ResourceManager.GetString("establishmentDigitalFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment Name.
        /// </summary>
        internal static string EstablishmentName {
            get {
                return ResourceManager.GetString("EstablishmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Styles.
        /// </summary>
        internal static string exploreStyles {
            get {
                return ResourceManager.GetString("exploreStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        internal static string Facilities {
            get {
                return ResourceManager.GetString("Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say goodbye to repeated printing — save ongoing menu costs for your restaurant..
        /// </summary>
        internal static string Feature_CostSaving_Desc {
            get {
                return ResourceManager.GetString("Feature_CostSaving_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Saving.
        /// </summary>
        internal static string Feature_CostSaving_Title {
            get {
                return ResourceManager.GetString("Feature_CostSaving_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers can access the menu via QR code easily without downloading an app..
        /// </summary>
        internal static string Feature_EasyAccess_Desc {
            get {
                return ResourceManager.GetString("Feature_EasyAccess_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Access.
        /// </summary>
        internal static string Feature_EasyAccess_Title {
            get {
                return ResourceManager.GetString("Feature_EasyAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce paper use and contribute to your restaurant’s environmental sustainability..
        /// </summary>
        internal static string Feature_EcoFriendly_Desc {
            get {
                return ResourceManager.GetString("Feature_EcoFriendly_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco-Friendly.
        /// </summary>
        internal static string Feature_EcoFriendly_Title {
            get {
                return ResourceManager.GetString("Feature_EcoFriendly_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo uploads for each dish.
        /// </summary>
        internal static string featureMenuItem1 {
            get {
                return ResourceManager.GetString("featureMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe or ingredient details for each item.
        /// </summary>
        internal static string featureMenuItem2 {
            get {
                return ResourceManager.GetString("featureMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and update your menu items, categories, and prices with ease..
        /// </summary>
        internal static string featureMenuManagementDescription {
            get {
                return ResourceManager.GetString("featureMenuManagementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Management.
        /// </summary>
        internal static string featureMenuManagementHeading {
            get {
                return ResourceManager.GetString("featureMenuManagementHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive design.
        /// </summary>
        internal static string featureMobileItem1 {
            get {
                return ResourceManager.GetString("featureMobileItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast loading times.
        /// </summary>
        internal static string featureMobileItem2 {
            get {
                return ResourceManager.GetString("featureMobileItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No app download required.
        /// </summary>
        internal static string featureMobileItem3 {
            get {
                return ResourceManager.GetString("featureMobileItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beautiful menus that look great on any device, especially smartphones..
        /// </summary>
        internal static string featureMobileOptimizedDescription {
            get {
                return ResourceManager.GetString("featureMobileOptimizedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Optimized.
        /// </summary>
        internal static string featureMobileOptimizedHeading {
            get {
                return ResourceManager.GetString("featureMobileOptimizedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate unique QR codes for each table that link directly to your digital menu..
        /// </summary>
        internal static string featureQrCodeDescription {
            get {
                return ResourceManager.GetString("featureQrCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code Menus.
        /// </summary>
        internal static string featureQrCodeHeading {
            get {
                return ResourceManager.GetString("featureQrCodeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited QR code generation.
        /// </summary>
        internal static string featureQRCodeItem1 {
            get {
                return ResourceManager.GetString("featureQRCodeItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category-specific codes.
        /// </summary>
        internal static string featureQRCodeItem2 {
            get {
                return ResourceManager.GetString("featureQRCodeItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printable high-resolution files.
        /// </summary>
        internal static string featureQRCodeItem3 {
            get {
                return ResourceManager.GetString("featureQRCodeItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you need to create and manage digital menus for your establishment..
        /// </summary>
        internal static string featuresSectionDescription {
            get {
                return ResourceManager.GetString("featuresSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features Designed for Establishments.
        /// </summary>
        internal static string featuresSectionHeading {
            get {
                return ResourceManager.GetString("featuresSectionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a QR code for your establishment that you can print and place on tables or display on screens..
        /// </summary>
        internal static string getQR {
            get {
                return ResourceManager.GetString("getQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string getStarted {
            get {
                return ResourceManager.GetString("getStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly growth of restaurants, users, and revenue. .
        /// </summary>
        internal static string Growth_PlatformDescription {
            get {
                return ResourceManager.GetString("Growth_PlatformDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Growth .
        /// </summary>
        internal static string Growth_PlatformTitle {
            get {
                return ResourceManager.GetString("Growth_PlatformTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sleek digital solution for present your menu online in an eco-friendly and efficient way.
        /// </summary>
        internal static string Hero_Subtitle {
            get {
                return ResourceManager.GetString("Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize your establishment menu now with TableTap.
        /// </summary>
        internal static string Hero_Title {
            get {
                return ResourceManager.GetString("Hero_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create beautiful digital menus, share them via QR codes, and give your customers a seamless experience..
        /// </summary>
        internal static string heroDescription {
            get {
                return ResourceManager.GetString("heroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Menus for Modern Establishments.
        /// </summary>
        internal static string heroHeading {
            get {
                return ResourceManager.GetString("heroHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does TableTap work?.
        /// </summary>
        internal static string howTableTapWork {
            get {
                return ResourceManager.GetString("howTableTapWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string inactive_status {
            get {
                return ResourceManager.GetString("inactive_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login Credentials.
        /// </summary>
        internal static string InvalidLoginCredentials {
            get {
                return ResourceManager.GetString("InvalidLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        internal static string legal {
            get {
                return ResourceManager.GetString("legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Payment Methods.
        /// </summary>
        internal static string manage_payment_methods {
            get {
                return ResourceManager.GetString("manage_payment_methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name.
        /// </summary>
        internal static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Type.
        /// </summary>
        internal static string MenuType {
            get {
                return ResourceManager.GetString("MenuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Name.
        /// </summary>
        internal static string method_name_label {
            get {
                return ResourceManager.GetString("method_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Wallet.
        /// </summary>
        internal static string MobileWallet {
            get {
                return ResourceManager.GetString("MobileWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly visit to the lists.
        /// </summary>
        internal static string monthlyVisit {
            get {
                return ResourceManager.GetString("monthlyVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Active Plan .
        /// </summary>
        internal static string MostActivePlan {
            get {
                return ResourceManager.GetString("MostActivePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Nav_Contact {
            get {
                return ResourceManager.GetString("Nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string Nav_FAQ {
            get {
                return ResourceManager.GetString("Nav_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Nav_Features {
            get {
                return ResourceManager.GetString("Nav_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How It Works.
        /// </summary>
        internal static string Nav_HowItWorks {
            get {
                return ResourceManager.GetString("Nav_HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string Nav_Stats {
            get {
                return ResourceManager.GetString("Nav_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payeer.
        /// </summary>
        internal static string Payeer {
            get {
                return ResourceManager.GetString("Payeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods .
        /// </summary>
        internal static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Requests.
        /// </summary>
        internal static string PaymentRequests {
            get {
                return ResourceManager.GetString("PaymentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        internal static string PayPal {
            get {
                return ResourceManager.GetString("PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Requests .
        /// </summary>
        internal static string PlanRequests {
            get {
                return ResourceManager.GetString("PlanRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string pricing {
            get {
                return ResourceManager.GetString("pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the plan that works best for your establishment..
        /// </summary>
        internal static string pricingSectionDescription {
            get {
                return ResourceManager.GetString("pricingSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple, Transparent Pricing.
        /// </summary>
        internal static string pricingSectionHeading {
            get {
                return ResourceManager.GetString("pricingSectionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string privacy {
            get {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce paper usage and contribute to the environmental sustainability of your establishment..
        /// </summary>
        internal static string reducePaperUsage {
            get {
                return ResourceManager.GetString("reducePaperUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered establishment.
        /// </summary>
        internal static string registeredEstablishment {
            get {
                return ResourceManager.GetString("registeredEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your establishment on the platform and start adding your listing easily..
        /// </summary>
        internal static string registerYourEstablishment {
            get {
                return ResourceManager.GetString("registerYourEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Plan.
        /// </summary>
        internal static string RequestedPlan {
            get {
                return ResourceManager.GetString("RequestedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Establishments Title.
        /// </summary>
        internal static string RequestingEstablishments_Title {
            get {
                return ResourceManager.GetString("RequestingEstablishments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        internal static string resetToDefault {
            get {
                return ResourceManager.GetString("resetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        internal static string Restaurants {
            get {
                return ResourceManager.GetString("Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Payment Method.
        /// </summary>
        internal static string save_method {
            get {
                return ResourceManager.GetString("save_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say goodbye to repetitive printing and save your establishment the periodic costs of lists..
        /// </summary>
        internal static string sayGoodbye {
            get {
                return ResourceManager.GetString("sayGoodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search payment methods....
        /// </summary>
        internal static string search_payment_methods {
            get {
                return ResourceManager.GetString("search_payment_methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔒 Secure and without the need for any app..
        /// </summary>
        internal static string secureWithoutApp {
            get {
                return ResourceManager.GetString("secureWithoutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a type.
        /// </summary>
        internal static string select_type {
            get {
                return ResourceManager.GetString("select_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Option.
        /// </summary>
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Establishments .
        /// </summary>
        internal static string SharedEstablishments {
            get {
                return ResourceManager.GetString("SharedEstablishments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do I need a special app?.
        /// </summary>
        internal static string specialApp {
            get {
                return ResourceManager.GetString("specialApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Cities .
        /// </summary>
        internal static string Stat_ActiveCities {
            get {
                return ResourceManager.GetString("Stat_ActiveCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Users .
        /// </summary>
        internal static string Stat_ActiveUsers {
            get {
                return ResourceManager.GetString("Stat_ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Revenue .
        /// </summary>
        internal static string Stat_MonthlyRevenue {
            get {
                return ResourceManager.GetString("Stat_MonthlyRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Restaurants .
        /// </summary>
        internal static string Stat_TotalRestaurants {
            get {
                return ResourceManager.GetString("Stat_TotalRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}% from last month .
        /// </summary>
        internal static string StatChange_LastMonth {
            get {
                return ResourceManager.GetString("StatChange_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} this month.
        /// </summary>
        internal static string StatChange_ThisMonth {
            get {
                return ResourceManager.GetString("StatChange_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stripe.
        /// </summary>
        internal static string Stripe {
            get {
                return ResourceManager.GetString("Stripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        internal static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Tab_Overview {
            get {
                return ResourceManager.GetString("Tab_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        internal static string Tab_Restaurants {
            get {
                return ResourceManager.GetString("Tab_Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string Tab_Revenue {
            get {
                return ResourceManager.GetString("Tab_Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Tab_Users {
            get {
                return ResourceManager.GetString("Tab_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features of TableTap.
        /// </summary>
        internal static string TableTapFeatures {
            get {
                return ResourceManager.GetString("TableTapFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is TableTap free?.
        /// </summary>
        internal static string tableTapFree {
            get {
                return ResourceManager.GetString("tableTapFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableTap numbers.
        /// </summary>
        internal static string tableTapNumbers {
            get {
                return ResourceManager.GetString("tableTapNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        internal static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Customizer.
        /// </summary>
        internal static string themeCustomizer {
            get {
                return ResourceManager.GetString("themeCustomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Requests .
        /// </summary>
        internal static string TotalRequests {
            get {
                return ResourceManager.GetString("TotalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dashboard.
        /// </summary>
        internal static string userDashboard {
            get {
                return ResourceManager.GetString("userDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Pricing.
        /// </summary>
        internal static string viewPricing {
            get {
                return ResourceManager.GetString("viewPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Why Choose TableTap? .
        /// </summary>
        internal static string whyChoose {
            get {
                return ResourceManager.GetString("whyChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, you can edit and add items whenever you want via the Dashboard..
        /// </summary>
        internal static string youCanEdit {
            get {
                return ResourceManager.GetString("youCanEdit", resourceCulture);
            }
        }
    }
}
